# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: dikikarim2010@gmail.com
author_name: Diki-karim
contract_name: hello_world
deployment_language: typescript
ide_vscode: true
preset_name: starter
project_name: algo-fulltask
use_python_black: true
use_typescript_jest: false

